config/routes.rb
Cinema::Application.routes.draw do

  
  
  put "voices/:increase_id" => "voices#increase", :as => "voices_increase"
  put "voices/:decrease_id" => "voices#decrease", :as => "voices_decrease"

  namespace :admin do
    resources  :admins
    resources  :configurables
    resources  :clients
    resources  :tasks
  end
  
  get 'admins/index'
    

  resources :answerfrommoderators
  resources :messagestoadministrators
  resources :messages
  resources :product_types
  resources :orders
  resources :line_items
  resources :carts
  
  resources :searches do 
    collection do
      post "search_film" => "searches#search_film"
    end
  end

  resources :folders
  resources :loads

  
  get 'home/index'

  get 'store/index'
  get 'store/all_category'
  get 'store/show'
  get 'store/contact'
  get 'line/increase',to: 'line_items#increase', as: :increase_line_item
  get 'line/decrease',to: 'line_items#decrease', as: :decrease_line_item
  get 'store/showlike'
  get '/change_locale/:locale', to: 'pages#change_locale', as: :change_locale
  

  resources :products do 
    collection do
      get "search" => "products#search"
    end
      resources :comments, module: :products do
    end
  end  
  
  resources :invitations do
    member do
      get "invitat/:id" =>"invitations#search_token", :as=>"search_token"
    end
  end
  
  
  resources :blogs do
    member do
      get "show_blog" => "blogs#show_blog"
    end 
    collection do
      get "search" => "blogs#search"
      get "home" => "blogs#home"
     
      get "about" => "blogs#about"
      get "contact" => "blogs#contact"
      get "features" => "blogs#features"
      get "services" => "blogs#services"
    end
   
  end
  
  resources :blogs, shallow: true  do
    resources :postings do
      member do
        get "show_posting" => "postings#show_posting"
      end
    end
  end
 
    
 

  resources :postings do
    resources :comments, module: :postings do
    end  
    collection do
      get :tags
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :posts do
    resources :questions
  end  

  resources :questions do
    resources :answers
  end  

  get "browse/:folder_id" => "loads#browse", :as => "browse"
  get "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder"
  delete 'user_delete/:id' => 'admins#delete_user', as: "delete_user"
  
  get "info_show_from_email/:user_id" => "infos#show_from_email", :as => "user_show"
  get "info_show_from_navbar/:user_id" => "infos#show_from_navbar", :as => "user_show_navbar"
  get "ban_the_user/:id" => "admins#ban_the_user", :as => "ban"
  
resources :infos 

devise_for :admins do
  collection do
   
  end
end
 resources :films, except: [:index] do
 
    resources :comments, module: :films do
      collection do
        get "new_with_info" => "comments#new_with_info"
      end
    end  
    collection do
     
      get "trailer" => "films#trailer"
      get "latest" => "films#latest"
      get "top_rated" => "films#top_rated"
      get "action" => "films#action"
      get "documental" => "films#documental"
      get "films/search" => "films#search", :as => "search_film"
      get "comedy" => "films#comedy", :as => "comedy"
      get "history" => "films#history", :as => "history"
      get "horror" => "films#horror", :as => "horror"
      get "other" => "films#other"
    end
    member do
      get "show_modal" => "films#show_modal"
      put "like"=>"films#upvote"
      put "dislike"=>"films#downvote"
     
    end
  end
   get "films/get/:id" => "films#get", :as => "download_film"

  resources :asets

  resources :actors do
     resources :comments, module: :films do
  end 
    end  
  get "loads/get/:id" => "loads#get", :as => "download"

  root 'home#all_film'

end

app/views/shared/_down.html.haml
= stylesheet_link_tag 'application', params[:controller], media: 'all', 'data-turbolinks-track' => true 

= javascript_include_tag 'application',params[:controller], 'data-turbolinks-track' => true
= csrf_meta_tags 

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to t('menu.languages.all_films'), root_path %>
        </li>
        <% if user_present? %>
          <li><%= link_to t('menu.languages.create_film'), new_film_path, 
          data: { modal: true }
            %>
          </li>
        <% else %>
          <li><%= link_to t('menu.languages.create_film'), new_user_registration_path
            %> 
          </li>
        <% end %>
        <li>
          <%= link_to t('menu.languages.advanced_search'), new_search_path, 
          data: { modal: true }  %>
        </li>
        <div class="navbar-form navbar-left" role="search">
          <%= form_tag(films_path, method: "get") do %>
            <div class="form-group">
              <%= text_field_tag :search, params[:short_search], :placeholder => t('menu.languages.search') %>
              <%= submit_tag "search"%>
            </div>
          <% end %>
        </div>
        <li>
          <%= link_to(image_tag('flag_sha.jpg', style: "height: 25px"), change_locale_path(:en)) %>
        </li>
     
        <li>
          <%= link_to(image_tag('Russia256.png', style: "height: 25px"), change_locale_path(:ru)) %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %> 
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown 
              <span class="caret">
              </span>
            </a>
            <ul class="dropdown-menu">
              <div class="list-group-item">
                <% if signed_in? %>
                  <li>

                    <%= ui_button 'info',  t(:show),user_show_navbar_path(current_user.id)%>
    

                  </li>
                <% else %>
                  <li>
                     <%= ui_button 'new',  t(:new),  new_info_path%>  
                            
                  </li>
                <% end %>
                <li> 
                   <%= ui_button 'destroy',  t('menu.languages.sign_out'),   destroy_user_session_path, :method => :delete  %>
                </li>
              </div> 
            </ul>
          </li> 
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <%= render "devise/sessions/new"%>
            <%= render "devise/registrations/new"%>    
          </ul>  
        <% end %>
      </ul>  
    </div>    
  </div>
</nav>
      


   
     