config/routes.rb
Cinema::Application.routes.draw do

  
  
  put "voices/:increase_id" => "voices#increase", :as => "voices_increase"
  put "voices/:decrease_id" => "voices#decrease", :as => "voices_decrease"

  namespace :admin do
    resources  :admins
    resources  :configurables
    resources  :clients
    resources  :tasks
  end
  
  get 'admins/index'
    

  resources :answerfrommoderators
  resources :messagestoadministrators
  resources :messages
  resources :product_types
  resources :orders
  resources :line_items
  resources :carts
  
  resources :searches do 
    collection do
      post "search_film" => "searches#search_film"
    end
  end

  resources :folders
  resources :loads

  
  get 'home/index'

  get 'store/index'
  get 'store/all_category'
  get 'store/show'
  get 'store/contact'
  get 'line/increase',to: 'line_items#increase', as: :increase_line_item
  get 'line/decrease',to: 'line_items#decrease', as: :decrease_line_item
  get 'store/showlike'
  get '/change_locale/:locale', to: 'pages#change_locale', as: :change_locale
  

  resources :products do 
    collection do
      get "search" => "products#search"
    end
      resources :comments, module: :products do
    end
  end  
  
  resources :invitations do
    member do
      get "invitat/:id" =>"invitations#search_token", :as=>"search_token"
    end
  end
  
  
  resources :blogs do
    member do
      get "show_blog" => "blogs#show_blog"
    end 
    collection do
      get "search" => "blogs#search"
      get "home" => "blogs#home"
     
      get "about" => "blogs#about"
      get "contact" => "blogs#contact"
      get "features" => "blogs#features"
      get "services" => "blogs#services"
    end
   
  end
  
  resources :blogs, shallow: true  do
    resources :postings do
      member do
        get "show_posting" => "postings#show_posting"
      end
    end
  end
 
    
 

  resources :postings do
    resources :comments, module: :postings do
    end  
    collection do
      get :tags
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :posts do
    resources :questions
  end  

  resources :questions do
    resources :answers
  end  

  get "browse/:folder_id" => "loads#browse", :as => "browse"
  get "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder"
  delete 'user_delete/:id' => 'admins#delete_user', as: "delete_user"
  
  get "info_show_from_email/:user_id" => "infos#show_from_email", :as => "user_show"
  get "info_show_from_navbar/:user_id" => "infos#show_from_navbar", :as => "user_show_navbar"
  get "ban_the_user/:id" => "admins#ban_the_user", :as => "ban"
  
resources :infos 

devise_for :admins do
  collection do
   
  end
end
 resources :films, except: [:index] do
 
    resources :comments, module: :films do
      collection do
        get "new_with_info" => "comments#new_with_info"
      end
    end  
    collection do
     
      get "trailer" => "films#trailer"
      get "latest" => "films#latest"
      get "top_rated" => "films#top_rated"
      get "action" => "films#action"
      get "documental" => "films#documental"
      get "films/search" => "films#search", :as => "search_film"
      get "comedy" => "films#comedy", :as => "comedy"
      get "history" => "films#history", :as => "history"
      get "horror" => "films#horror", :as => "horror"
      get "other" => "films#other"
    end
    member do
      get "show_modal" => "films#show_modal"
      put "like"=>"films#upvote"
      put "dislike"=>"films#downvote"
     
    end
  end
   get "films/get/:id" => "films#get", :as => "download_film"

  resources :asets

  resources :actors do
     resources :comments, module: :films do
  end 
    end  
  get "loads/get/:id" => "loads#get", :as => "download"

  root 'home#all_film'

end

app/models/home.rb
class Home < ActiveRecord::Base
	 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
    
  def all_film
    @films = Film.search(params[:search]).paginate(:page => params[:page], :per_page => Configurable[:films_per_page])
    @resourse='Film'
  end	

end

app/helpers/home_helper.rb
module HomeHelper
   
  
end

app/views/home/_action_buttons.haml
-# Tools for the app
= link_to( 'PivotalTracker', pivotal_tracker_project, :target => 'ext_tools') if pivotal_tracker_project
= link_to( 'Github', github_project, :target => 'ext_tools' ) if github_project

-# Actions
= link_to( t(:new_page), new_page_path ) if can? :manage, Page
= link_to( t(:new_blog), new_blog_path ) if can? :manage, Blog
= link_to( t(:manage_templates), templates_pages_path) if can? :manage, PageTemplate
= link_to( t(:manage_menus), site_menus_path) if can? :manage, SiteMenu

-# Communications
= link_to( (twitter_name||'Twitter'), twitter_link, :target => 'ext_tools') if twitter_link

-# Draft Mode
- if current_role?(:author)
  - if session[:draft_mode]
    = link_to t(:hide_drafts), draft_mode_path(0)
  - else
    = link_to t(:show_drafts), draft_mode_path(1)

app/views/home/_all_film.html.erb
<%=link_to "google", user_omniauth_authorize_path(:google_oauth2)%>
<%=link_to "olesa", user_omniauth_authorize_path(:facebook)%>

<!DOCTYPE html>



<html lang="en">
<% title('All films') %>
<meta charset="utf-8">





<body>
<!-- wrapper -->
<div id="wrapper">
  <div class="light-bg">
    <!-- shell -->
    <div class="shell">
      <!-- header -->
    <%= render "home/head"%>
      <!-- end of header -->
      <!-- main -->
      <div class="main">
        <!-- content -->
        <section class="content">
          
          <% @films.each do |film| %>
     
            <div class="post">
              <!-- post-inner -->
              <div class="post-inner">
                <header>
                  <h2><a> <%= link_to "#{film.title}", film_path(film) %></a></h2>
                  <p class="tags"><a href="#">FAMILY</a> <a href="#">COMEDY</a> <a href="#">ANIMATION</a> </p>
                  <div class="cl">&nbsp;</div>
                </header>

              <div class="row">
                <div class="col-md-8">
                  <div class="img-holder"> <%= link_to image_tag(film.uploaded_file.url(:preview)), film_path(film)  %>
                  </div>
              
                  <div class="meta">
                    <p class="date"><%= film.created_at %> 
                      <a><%= link_to info_from_email(film), info_path(info_by_email(film)) %>
                      </a> 
                      <a><%= link_to "Download", film_path(film) %>
                      </a> 
                          <% if signed_in? %>
                            <% if  can_manage(current_user.films, film, Film) %>
                              <%= link_to  t('activerecord.attributes.edit'), edit_film_path(film) %>
                              <%= link_to t('activerecord.attributes.delete'), film, method: :delete, data: { confirm: 'Are you sure?' } %>
                            <% end %>
                          <% end %>
                           

                      </a>
                    </p>

                    <div class="right">
                      <div class="rating-holder">
                        <%=render partial: "voices/like_dislike", locals: {resourse_number: film, name_controller: Film} %>
                      </div>
                      <div class="comments"><%= link_to "#{film.comments.count} comments", film_path(film) %> 
                      </div>
                    </div>

                    <div class="cl">
                      &nbsp;
                    </div>
                  </div>

                </div>

                <div class="col-md-4">
                  <div class="text_description">
                    <%= insert_text(film.description,490)%>
                  </div>
                  <%= ui_button 'read', t(:show),show_modal_film_path(film), data: { modal: true } %>
                </div>
              </div>
            
          </div>
          </div>
          <% end %>
          <div class="pagination">
            <ul>
      
              <li class="active">
                <a>
                  <%unless Array.present?%>
                    <%= render_pagination_box(@films) %> 
                  <%end%>
                </a>
              </li>
            </ul>
          </div>
        </section>

        <!-- end of content -->
        <!-- sidebar -->
       <%= render "home/down"%>
        <!-- end of sidebar -->
        <div class="cl">&nbsp;</div>
      </div>
      <!-- end of main -->
    
    </div>
    <!-- end of shell -->
  </div>
</div>
<!-- end of wrapper -->
</body>
</html>

app/views/home/_down.html.erb
<aside class="sidebar">
  <div class="widget">
    <h3 class="widgettitle">Genres</h3>
    <ul>
      <li><a><%=link_to "Action", action_films_path%></a></li>
      <li><a><%=link_to "Comedy", comedy_films_path%></a></li>
      <li><a><%=link_to "Documental", documental_films_path%></a></li>
      <li><a><%=link_to "History", history_films_path%></a></li>
      <li><a><%=link_to "Horror", horror_films_path%></a></li>
      <li><a><%=link_to "Mystery", other_films_path%></a></li>
      <li><a><%=link_to "War", other_films_path%></a></li>
      <li><a><%=link_to "Western", other_films_path%></a></li>
      <li><a><%=link_to "Adventure", other_films_path%></a></li>
      <li><a><%=link_to "Crime", other_films_path%></a></li>
      <li><a><%=link_to "Fantasy", other_films_path%></a></li>
      <li><a><%=link_to "Thriller", other_films_path%></a></li>
    </ul>
  </div>
  <div class="widget">



    <h3 class="widgettitle">Opening This Week
    </h3>
    <ul>
    <% last_film.each do |last_film| %>
      <li>
        <a href="#"><%= last_film.title %> 
          <strong><%= time_ago_in_words(last_film.created_at)%>
          </strong>
        </a>
      </li>
    <% end %>

    </ul>
  </div>
</aside>

app/views/home/_footer.html.erb
<div class="">
  <nav class="-nav">
    <ul>
      <li><a href="#">Show All</a></li>
      <li><a href="#">Latest Movies</a></li>
      <li><a href="#">Top Rated</a></li>
      <li><a href="#">Most Commented</a></li>
    </ul>
  </nav>
  <p class="copy">Copyright &copy; 2012 <span>|</span> Sitename. Design by <a target="_blank" href="http://chocotemplates.com">ChocoTemplates</a></p>
</div>

app/views/home/_head.html.erb
      <div class="header">
        <!-- socials -->
        <div class="socials"> <a href="#" class="facebook-ico">facebook-ico</a> <a href="#" class="twitter-ico">twitter-ico</a> <a href="#" class="you-tube-ico">you-tube-ico</a> </div>
        <!-- end of socials -->
        <h1 id="logo"><a href="#">Moviereviews</a></h1>
        <!-- navigation -->
        <nav id="navigation">
          <ul>
            <li><a><%=link_to "SHOW ALL", films_path%></a></li>
            
            <li><%= link_to 'LATEST ', latest_films_path%></li>
            <li><%= link_to 'TOP RATED ', top_rated_films_path%></li>
            <li><a><%= link_to 'ADD FILM', new_film_path%></a></li>
          </ul>
        </nav>
        <!-- end of navigation -->
        <div class="cl">&nbsp;</div>
      </div>

app/views/home/_interpreter_help.haml
= link_to 'Markdown?', "http://daringfireball.net/projects/markdown/syntax" , :target => :blank
= link_to 'Textile?',  "http://www.textism.com/tools/textile/"              , :target => :blank

app/views/home/_load_more.haml
%p#load_more.load_more
    - if resources.total_pages > resources.current_page
        = link_to_function( t(:load_more),                        |
             "insert_load_button( 'load_more','#{t(:loading)}',"+ |
             "'#{path}?page=#{resources.current_page+1}&order=#{params[:order]}&direction=#{params[:direction]}'"+        |
             ");return false;",                                   |
             :id => 'load_more_link')                             |

app/views/home/all_film.html.erb
<%=render partial: "home/all_film"%>

app/views/home/icndex.html.erb
tdfgthhghdf


<!DOCTYPE html>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
  <meta charset="UTF-8">
  <title>Bhaccasyoniztas Beach Resort Website Template</title>

</head>
<body>
  <div id="background">
    <div id="page">
      <div id="header">
        <div id="logo">
          <a href="index.html"><img src="/assets/all_film/logo.png" alt="LOGO" height="112" width="118"></a>
        </div>
        <div id="navigation">
          <ul>
            <li class="selected">
              <a href="index.html">Home</a>
            </li>
            <li>
              <a href="about.html">About</a>
            </li>
            <li>
              <a href="rooms.html">Rooms</a>
            </li>
            <li>
              <a href="dives.html">Dive Site</a>
            </li>
            <li>
              <a href="foods.html">Food</a>
            </li>
            <li>
              <a href="news.html">News</a>
            </li>
            <li>
              <a href="contact.html">Contact</a>
            </li>
          </ul>
        </div>
      </div>
      <div id="contents">
        <div id="adbox">
          <img src="/assets/all_film/sea-sound.jpg" alt="Img">
          <h1>Enjoy the Summer with Us!</h1>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div id="main">
              <div id="testimonials" class="box">
                <div>
                  <div>
                    <h3>Testimonials</h3>
                    <p>
                      “In hac habitasse platea dictumst. Integer purus justo, egestas eu consectetur eu, cursus in tortor. Quisque nec nunc ac mi ultrices iaculis. Aenean quis elit mauris, nec vestibulum lorem.” <span>- <a href="index.html">Juan De La Cruz</a></span>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div id="sidebar">
              <div class="section">
                <a href="foods.html"><img src="/assets/all_film/food.png" alt="Img"></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="">
      <div>
        <ul class="navigation">
          <li class="active">
            <a href="index.html">Home</a>
          </li>
          <li>
            <a href="about.html">About</a>
          </li>
          <li>
            <a href="rooms.html">Rooms</a>
          </li>
          <li>
            <a href="dives.html">Dive Site</a>
          </li>
          <li>
            <a href="foods.html">Food</a>
          </li>
          <li>
            <a href="news.html">News</a>
          </li>
          <li>
            <a href="contact.html">Contact</a>
          </li>
        </ul>
        <div id="connect">
          <a href="http://pinterest.com/fwtemplates/" target="_blank" class="pinterest"></a> <a href="http://freewebsitetemplates.com/go/facebook/" target="_blank" class="facebook"></a> <a href="http://freewebsitetemplates.com/go/twitter/" target="_blank" class="twitter"></a> <a href="http://freewebsitetemplates.com/go/googleplus/" target="_blank" class="googleplus"></a>
        </div>
      </div>
      <p>
        © 2023 by BHACCASYONIZTAS BEACH RESORT. All Rights Reserved
      </p>
    </div>
  </div>
</body>
</html><a href="sac sad" onclick="paintIt(this, '#990000')">Paint it red</a>







<div class="row">
  

  <div class="col-md-6">
      <div class="thumbnail thumb-box">
          <h2 style="text-align:center">
          <p class="text">Action</p>
            <div class="ris"><%= link_to image_tag("2/1.jpg", alt: 'Site Logo', class: "pict"), trash_films_path %>
            </div>
          </h2>
      </div>
  </div>


  <div class="col-md-2">
  </div>



  <div class="col-md-6">
  	<div class="thumbnail thumb-box">
                 <h2 style="text-align:center">
             <p class="text">Thriler</p>
  
              <div class="ris"><%= link_to image_tag("2/2.jpg", alt: 'Site Logo', class: "pict"), triler_films_path %>
              </div>


            </h2>
     </div>
  </div>
</div>


<div class="row">
<div class="col-md-6">
      <div class="thumbnail thumb-box">
           <h2 style="text-align:center">
       <p class="text">Documental</p>

          <div class="ris">
  	<%= link_to image_tag("2/3.jpg", alt: 'Site Logo', class: "pict"), documental_path %>
    </div>
  </h2>
  </div>
  </div>



<div class="col-md-2">
</div>



<div class="col-md-6">
  	  <div class="thumbnail thumb-box">
                 <h2 style="text-align:center">
             <p class="text">Serial</p>
                    <div class="ris">
    	<%= link_to image_tag("2/4.jpg", alt: 'Site Logo', class: "pict"), serial_films_path %>
        </div>
     </h2>
  </div>
  </div>
 </div>

app/views/home/index.js.erb
/* REVIEW: This file is needed for any endles-loading view. Is there a way to unify this, so we have it only once? */
$(".pagination_box").html('<%= escape_javascript(will_paginate(@postings)) %>');

$('.load_more').before( '<div id="page<%= @postings.current_page -%>" style="clear: both; display: none;">'+
                          '<p class="page_seperator"><%= @postings.current_page -%>'+
                          '/<%= @postings.total_pages -%></p>'+
                          '<%= escape_javascript(render(:partial => @postings, :locals => {:blog => @blog})) -%>'+
                          '</div>');

<% if is_on_last_page(@postings) %>
   $('#load_more').html( '<%=  escape_javascript(link_to_function(t(:load_more),"insert_load_button( 'load_more','#{t(:loading)}',"+
        "'#{@path}')", :id => "load_more_link" )) -%>');
   $('#page<%= @postings.current_page -%>').slideDown();
   setTimeout("checkScroll()", 500);
<% else %>
  $('#page<%= @postings.current_page -%>').slideDown();
  $('#load_more').html('<p style="text-align:center; margin-top: 20px;"><%= escape_javascript(t(:end_of_list)) -%></p>');
<% end %>

app/views/home/tags.haml
- title 'Postings tagged with ' + params[:tag]

#tagged_postings
  = render @postings